### ISSUE TITLE
Add support for php 8.1.27

### ISSUE THREAD

**Issue by aaronkelton** [adriansuter/php-autoload-override#43]
I tried requiring this package today using `composer require --dev adriansuter/php-autoload-override 1.0`

```
  [InvalidArgumentException]                                                               
  Package adriansuter/php-autoload-override at version 1.0 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:                         
    - adriansuter/php-autoload-override 1.0 requires php ^7.1 which does not match your installed version 8.1.27.
```

I noticed you have tags up to 1.4, so I ended up running this that I think worked `composer require --dev --ignore-platform-reqs -W adriansuter/php-autoload-override 1.4`

**Comment by adriansuter** [comment]
Thanks. Just updated the installation instructions.
